site_name: MkDocs Demo
site_url: https://github.com/myspotontheweb/mkdocs-demo
nav:
    - Home: index.md
    - Blog: blog/index.md
    - About: about.md
theme: material

plugins:
  - diagrams
  - search
  - blog:
      blog_toc: true
      archive_toc: true
      post_excerpt: required
  - kroki:
      DownloadImages: true
      DownloadDir: assets/images
