site_name: MkDocs Demo
site_url: https://myspotontheweb.github.io/mkdocs-demo
repo_url: https://github.com/myspotontheweb/mkdocs-demo
repo_name: myspotontheweb/mkdocs-demo
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Blog: blog/index.md
  - About: about.md

theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
    - content.action.edit

markdown_extensions:
  - toc
  - admonition

plugins:
  - diagrams
  - search
  - blog:
      blog_toc: true
      archive_toc: true
      post_excerpt: required
  - kroki:
      DownloadImages: true
      DownloadDir: assets/images
